try{
    consol.log('Hello')
} catch(error){
    console.log('Found an error')
    console.log(`Error message is ${error}`)
}